---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: api-api-api.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: expenses-repo-service
                port:
                  number: 443
    - host: finances.api-api-api.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: expenses-repo-service
                port:
                  number: 443
  tls:
    - hosts:
        - api-api-api.com
        - finances.api-api-api.com
      secretName: cert-secret-name
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    email: catprogrammer.vlad@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
spec:
  secretName: cert-secret-name
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  isCA: false
  dnsNames:
    - api-api-api.com
    - finances.api-api-api.com
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
