apiVersion: v1
kind: Secret
metadata:
  name: superuser-secret
type: kubernetes.io/basic-auth
data:
  username: cG9zdGdyZXM= # "postgres" base64 encoded
  password: c3VwZXJzZWNyZXRwYXNz # Replace with your own base64 encoded password

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: kubernetes.io/basic-auth
data:
  username: YXBw # "app" base64 encoded
  password: YXBwZXBhc3M= # Replace with your own base64 encoded password

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-finances
spec:
  instances: 3
  superuserSecret:
    name: superuser-secret
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-secret
  storage:
    size: 1Gi
