# PostgreSQL Cluster Configuration
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-finances
spec:
  instances: 3
  superuserSecret:
    name: superuser-secret
  bootstrap:
    initdb:
      database: nekoneki
      owner: nekoneki
      secret:
        name: nekoneki-secret
      postInitSQL:
        - "ALTER USER nekoneki WITH SUPERUSER;"
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: cluster-example-rw-lb
            spec:
              type: LoadBalancer
  storage:
    size: 1Gi

---
# Secret for PostgreSQL Owner
apiVersion: v1
kind: Secret
metadata:
  name: nekoneki-secret
type: kubernetes.io/basic-auth
data:
  username: bmVrb25la2k= # Base64 encoded 'nekoneki'
  password: bmVrb25la2k= # Base64 encoded 'nekoneki'
