apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  labels:
    app: {{ .Values.app }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 443
      targetPort: 443
  selector:
    app: {{ .Values.app }}
