name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    environment: dev-aws
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # - name: Get short commit hash
      #   id: commit
      #   run: echo "short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build, Tag, and Push Docker Image
        env:
          CICD_GIT_COMMIT: ${{ steps.commit.outputs.short }}
        run: |
          docker build -t bot-repo:latest ./bot
          docker tag bot-repo:latest 014498641718.dkr.ecr.eu-north-1.amazonaws.com/bot-repo:$CICD_GIT_COMMIT
          docker push 014498641718.dkr.ecr.eu-north-1.amazonaws.com/bot-repo:$CICD_GIT_COMMIT

      - name: Update kube config
        run: aws eks update-kubeconfig --region eu-west-1 --name ex-eks

      - name: Deploy to EKS
        env:
          CICD_GIT_COMMIT: ${{ steps.commit.outputs.short }}
        run: |
          envsubst < ./k8s | kubectl apply -f -
